const statusLabels: Record<string, string> = {
  high: "高优先级",
  medium: "中优先级",
  low: "低优先级",
  blocker: "阻断",
  continuity: "连续性",
  emotion: "情绪",
  focus: "重点",
  hook: "钩子",
  reader_promise: "读者承诺",
  relationship: "关系",
  relationships: "关系",
  readiness: "准备度",
  memory: "记忆",
  context: "上下文",
  quality: "质量",
  editorial: "编辑",
  review: "审阅",
  architecture: "作品架构",
  blueprint: "章节蓝图",
  draft: "草稿",
  gate: "接收检查",
  accept: "接收",
  next_chapter: "下一章",
  risk: "有风险",
  clear: "正常",
  insufficient: "样本不足",
  on_track: "正常推进",
  at_risk: "有风险",
  overdue: "已逾期",
  planned: "计划中",
  retired: "已停用",
  suggested: "建议",
  in_progress: "进行中",
  idle: "未开始",
  paused: "已暂停",
  waiting_confirm: "等待确认",
  lesson: "写作经验",
  recommended: "推荐",
  viable: "可用",
  risky: "有风险",
  ready: "已就绪",
  block: "已阻断",
  blocked: "已阻断",
  unknown: "状态未知",
  pass: "通过",
  warn: "需注意",
  missing: "缺失",
  skipped: "已跳过",
  active: "生效",
  candidate: "候选",
  completed: "已完成",
  failed: "失败",
  cancelled: "已取消",
  running: "运行中",
  pending: "等待中",
  proposed: "待确认",
  accepted: "可写入",
  rejected: "已跳过",
  applied: "已应用",
  defer: "需人工确认",
  alliance: "同盟",
  family: "亲情",
  friendship: "友情",
  mentorship: "师徒",
  rivalry: "竞争",
  romance: "情感",
  other: "其他",
  established: "关系建立",
  maintained: "关系延续",
  shifted: "关系变化",
  "explicit-shift": "明确转折"
};

export function statusLabel(value: unknown, fallback = "状态未知") {
  const text = String(value ?? "").trim();
  if (!text) {
    return fallback;
  }
  return statusLabels[text.toLowerCase()] ?? (/[\u4e00-\u9fff]/.test(text) ? text : fallback);
}
